import 'package:flutter/material.dart';
import 'package:core/core.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

class CreateCourseDialog extends StatefulWidget {
  final AdminRepository repository;
  final VoidCallback onSuccess;

  const CreateCourseDialog({
    super.key,
    required this.repository,
    required this.onSuccess,
  });

  @override
  State<CreateCourseDialog> createState() => _CreateCourseDialogState();
}

class _CreateCourseDialogState extends State<CreateCourseDialog> {
  final _titleController = TextEditingController();
  final _descriptionController = TextEditingController();
  final _priceController = TextEditingController();
  bool _isLoading = false;
  String? _error;

  Future<void> _submit() async {
    if (_titleController.text.isEmpty || _priceController.text.isEmpty) {
      setState(() => _error = 'Title and Price are required');
      return;
    }

    setState(() {
      _isLoading = true;
      _error = null;
    });

    try {
      final course = Course(
        id: '', // Will be generated by DB
        title: _titleController.text,
        description: _descriptionController.text,
        price: double.tryParse(_priceController.text) ?? 0.0,
        thumbnail: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800',
        subjects: [],
        isActive: true,
        organizationId: '', // Will be handled by repository
      );

      await widget.repository.createCourse(course);
      widget.onSuccess();
    } catch (e) {
      setState(() {
        _isLoading = false;
        _error = e.toString();
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20.r)),
      title: Text('Create New Course', style: AppTextStyles.h3),
      content: SizedBox(
        width: 450.w,
        child: SingleChildScrollView(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              AppTextField(
                controller: _titleController,
                label: 'Course Title',
                hint: 'e.g. Master Mathematics',
                prefixIcon: const Icon(Icons.title_rounded),
              ),
              SizedBox(height: 16.h),
              AppTextField(
                controller: _descriptionController,
                label: 'Description',
                hint: 'Enter course overview...',
                maxLines: 3,
              ),
              SizedBox(height: 16.h),
              AppTextField(
                controller: _priceController,
                label: 'Price (\$)',
                hint: '0.00',
                keyboardType: TextInputType.number,
                prefixIcon: const Icon(Icons.attach_money_rounded),
              ),
              if (_error != null) ...[
                SizedBox(height: 16.h),
                Text(_error!, style: const TextStyle(color: Colors.red, fontSize: 12)),
              ],
            ],
          ),
        ),
      ),
      actions: [
        TextButton(
          onPressed: () => Navigator.pop(context),
          child: Text('Cancel', style: TextStyle(color: AppColors.textSecondary)),
        ),
        AppButton(
          text: 'Publish Course',
          isFullWidth: false,
          width: 160.w,
          isLoading: _isLoading,
          onPressed: _submit,
        ),
      ],
    );
  }
}
